// Controle op de meegeleverde kaart. Geen bouwstap, geen framework: gewone
// browser-javascript, dus we kijken vooral naar echte fouten.
export default [
  {
    files: ["custom_components/nos_teletekst/frontend/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        customElements: "readonly",
        HTMLElement: "readonly",
        ResizeObserver: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        console: "readonly",
        Image: "readonly",
        Number: "readonly",
        Math: "readonly",
        JSON: "readonly",
        Array: "readonly",
        String: "readonly",
        Object: "readonly",
        Promise: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        Date: "readonly",
        innerWidth: "readonly",
        innerHeight: "readonly",
        addEventListener: "readonly",
        removeEventListener: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "warn",
      "no-dupe-keys": "error",
      "no-dupe-class-members": "error",
      "no-unreachable": "error",
      "no-self-assign": "error",
      "no-fallthrough": "error",
      "no-constant-condition": "warn",
      "no-async-promise-executor": "error",
      "require-atomic-updates": "warn",
      eqeqeq: ["warn", "smart"],
    },
  },
];
